### PR TITLE
Fix share button

### LINKED ISSUE #15: Fav counter is covered by the share button on Android

### PR DESCRIPTION
**Pull request by JakubValtar**
Looks much better:

The share button, if present, steals `margin-left: auto` from the dropdown menu.

The code is ugly, if you know a better way to handle the presence of the share button with css, please go for it.

Fixes #15

### CODE REVIEW

**Comment by neauoire** [comment]
We should just hide it.
I don't even see that button actually.

**Comment by JakubValtar** [comment]
Does not work, the button has width and height and stays there.

```html
<button aria-label="Share" title="Share" class="status__action-bar-button icon-button" tabindex="0"
    style="font-size: 18px; width: 23.1429px; height: 23.1429px; line-height: 18px;">
  <i class="fa fa-fw fa-share-alt" aria-hidden="true"></i>
</button>
```

**Comment by neauoire** [comment]
aight, at least it won't be in the way anymore.

**Comment by JakubValtar** [comment]
Let's just hide it, it's ugly anyway and I figured out how to have the same functionality without it.

I used `.status__action-bar-button[aria-label="Share"] { display: none; }`, sending a new PR.

**Pull request merged**
