### PR TITLE
Audio & video player styling

### PR DESCRIPTION
**Pull request by lectronice**
Various tweaks for a greyscale & cyan player.

### CODE REVIEW

**Comment by neauoire** [comment]
I vote to give style writing access to lectronice

**Comment by lectronice** [comment]
I'd be happy to contribute :)

**Comment by SomniusTiger** [comment]
Oh, right, this exists! Thanks for your patience. Lemme go ahead and merge this, and thanks for your hard work :3

In the future, could you make pull requests to [this repo here](https://github.com/merveilles/merveilles-town)? You’ll want to edit [this file](https://github.com/merveilles/merveilles-town/blob/merveilles/app/javascript/styles/merveilles.scss) in particular :D

That way, I can merge things in a bit quicker to the existing styles and deploy really easily!

**Comment by lectronice** [comment]
Okay, no problem, thanks!

**Pull request merged**
