### PR TITLE
Adds initial debugging playbook doc, without screenshots

### PR DESCRIPTION
**Pull request by SomniusTiger**
Adds a guide to some common issues for administrators for The Town!

### CODE REVIEW

**Comment by SomniusTiger** [comment]
Hey there @neauoire! Let me know if this goes over all the things you want to go over, or if there's anything confusing, and let me know if I can supply any further screenshots.

I think the screenshots aren't showing up right in the rich view of the PR because this hasn't been merged in yet, but that should be fixed once it's all good to go!

**Comment by SomniusTiger** [comment]
Also check out that pull request number, nice

**Review by neauoire — APPROVED** [review]
It's perfect! Do you think we should ask for some extra help? New mods and admins who can improve support coverage for the instance when we're both offline? We're both on the exact same timezone now that've moved to BC.

**Comment by SomniusTiger** [comment]
Having more folks from different timezones can definitely help, for sure. We can ask around! :D

**Pull request merged**
